//tao phuong thuc post
POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "Khang Khung",
    "email": "nguyenbaokhang8911@gmail.com"
}

###
//Xoa khoa hoc
DELETE http://localhost:3001/school/courses/1
###

//Xoa nguoi dung
DELETE http://localhost:3001/school/users/1
###
